### ISSUE TITLE
Remaining issues to the website

### ISSUE THREAD

**Issue by oeway** [bioimage-io/collection-bioimage-io#418]
Hi @FynnBe It appears you have been making good progress on fixing the issues. I am not sure if it's because of the caching or we need to wait for more time for the changes to take effect, but here are the 3 remaining issues (same as before actually):

1. Some BioEngine Apps are missing: https://github.com/imjoy-team/bioimage-io-models/blob/1ef7f2950acd2fd62a9939beec5fe3ac392f44fd/manifest.bioimage.io.yaml#L50-L52
2. Related to the resolving priority we discussed, some BioEngine Apps having the same collection name: https://bioimage.io/#/?type=application&id=imjoy%2Fimagej.js (The info from the ImJoy plugin file should have higher priority than the collection info)
3. The models in the deepimagej repo are not displayed, the models tab has only two pages at the moment, normally we should have more.

**Comment by FynnBe** [comment]
1. fixed: https://bioimage.io/#/?type=application&id=imjoy%2Fhpa-single-cell
2. fixed: https://bioimage.io/#/?type=application&id=imjoy%2Fimagej.js
3. the collection RDF validation is now slightly stricter, so the deepimagej models gone again, because they don't adhere to the spec (missing `type: model`) This is a known problem and is fixed while uploading them to zenodo... otherwise we could fix it in the deepimagej repo, if we can't wait for them to be on zenodo any longer....
