### ISSUE TITLE
External CI integration

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/collection-bioimage-io#54]
We want to integrate external CI results here. The main use case is to run new models with CI defined by the partners, e.g. to check if the model runs in deepimageJ or ilastik. For now, we have discussed two potential ideas for integration:
1. The partner orgs make PRs to this repository (collection-bioimage-io) to communicate their CI status
2. Partners define where the CI results are stored on their website and we pull the information in here

**Comment by constantinpape** [comment]
cc @oeway @FynnBe

**Comment by FynnBe** [comment]
Having in mind how this collection repo is handling this atm, this could roughly look like this:


[only option 2.] partner collection rdf specifies a summary folder: e.g. in  ilastik collection config: https://github.com/ilastik/bioimage-io-models/blob/fa5eb8c22c93d915c6df079f5269687b618707b9/collection.yaml#L31
```yaml
config:
    validation_summaries: https://github.com/ilastik/bioimage-io-models/tree/gh-pages/validation_summaries
```
the content of the validation summary folder would be similar to https://github.com/bioimage-io/collection-bioimage-io/tree/gh-pages/resources , i.e. store `validation_summaries/resource_id/validation_summary_{validation_name}.yaml` files that we can glob over. `{validation_name}` is any string, e.g. `ilastik-1.3.0` to distinguish multiple validation summaries from that partner.

[1./2.] the content of those `validation_summary.yaml` files would also be analog to e.g. https://github.com/bioimage-io/collection-bioimage-io/tree/gh-pages/resources/10.5281/zenodo.5744490
which is the output of the validator (https://github.com/bioimage-io/spec-bioimage-io/blob/5f00da1d318af583f2480f01deeea25062866580/bioimageio/spec/commands.py#L39-L40
; without nested errors; let's not nest collections just yet):
- `error` (nested) dict of string keys and values to indicate where/what went wrong
- `warnings` analog to error
- `traceback` of error (especially for unexpected errors; more ineteresting for debugging than showing on the website)
- plus an additional  `name` key for a human readable short description of what this validation tested (e.g. "Reproduced test outputs from test inputs with the ilastik 1.3.0 dependencies")

[1.] the `validation_summary.yaml`  are deployed (via PR or directly)) to /bioimage-io/collection-bioimage-io/gh-pages

Atm I prefer option 2 as it seems cleaner

**Comment by constantinpape** [comment]
We had a long discussion with @FynnBe and @oeway on this yesterday. I can't summarize all of it here, but my two take aways are: we probably need to iterate on this a bit before we can find a really good solution and it would be good to start laying out potential high-level designs here. (And then identifying potential issues).
A possible design I could see working (pretty close to what @FynnBe has proposed):
- `collection-bioimage-io` stores the updated rdf on gh-pages for each model (more general resource, but I'll just talk about model for now to keep this simpler)
- the partner repos specify the location where they store their CI outputs
- the partner repo's CI regularly go through all models on `collection-bioimage-io` (specifically the updated rdf on gh-pages) and for each one:
  - check if this is a model that needs to be validated (e.g. partners may only accept for certain weight types)
  - if no, we can either generate a generic CI report for this model, or no report at all with the implicit meaning that it means partner does not support this model
  - if yes, check if the model has been checked already (by comparing file or commit hash, see below)
  - if needs to be checked again, run CI and store the CI result, including an identifying hash for the rdf (either the file hash or hash of the last commit that has changed the file)
- the `collection-bioimage-io` repo goes through all the partner locations in main ci and collects their CI messages; it can detect if the CI result is out of date due to the hash

**Comment by FynnBe** [comment]
Together with @oeway I had a closer look at the workflow dispatch funcitonality of github workflows and it turns out to be fairly straight forward to trigger a workflow in another repository. I am experimenting with that already (see [here](https://github.com/ilastik/bioimage-io-resources/blob/main/.github/workflows/validate_bioimageio_resources.yaml)). The only thing the partner needs to do additionally is to invite the @bioimageiobot to collaborate (write access (or less?) is sufficient). The partner CI can afterwards trigger the collection main workflow again, so the delay to deploy the validation result is minimal.

With this in mind some small changes and additions to your outline: 
- each partner specifies which resource types they want to validate
- we check for missing partner validations whenever we build (and trigger the partner ci if any are detected; partner CI probably should have a concurrency key in their workflow to avoid parallel runs)

Maybe we have to rethink storing the validation summary directly in the rdf as this makes detecting real changes unecessarily hard (both with file hash and last change commit hash). We could go around this by removing the `config:bioimageio` section before computing the file hash or simply saving the validation summary separately.

**Comment by FynnBe** [comment]
we have test_summary.yaml files like [this one](https://github.com/bioimage-io/collection-bioimage-io/blob/gh-pages/rdfs/10.5281/zenodo.5869899/6321179/test_summary.yaml) now
